language: python
sudo: false
python:
  - 3.5
addons:
  postgresql: "9.4"
services:
  - redis-server
install:
  - pip install virtualenv
  # avoid building frontend since npm is broken on Travis
  - mkdir static
  - touch static/index.html
  - python manage.py bootstrap --develop
  - .env/bin/pip install -e git://github.com/slash-testing/backslash-python.git@master#egg=backslash-python
script: travis_retry python manage.py travis-test
