language: python
sudo: false
python:
  - 3.4 
addons:
  postgresql: "9.4"
services:
  - redis-server
addons:
  postgresql: "9.4"
install:
  - pip install virtualenv
script: travis_retry python manage.py travis-test
